"""Initial migration

Revision ID: 0d237c654619
Revises: 
Create Date: 2026-02-04 18:54:58.100812

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0d237c654619'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('User',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('birth_year', sa.Integer(), nullable=True),
    sa.Column('gender', sa.String(), nullable=True),
    sa.Column('profile_image', sa.String(), nullable=True),
    sa.Column('referral_code', sa.String(), nullable=True),
    sa.Column('contact_warning_count', sa.Integer(), nullable=True),
    sa.Column('contact_warning_updated_at', sa.DateTime(), nullable=True),
    sa.Column('is_banned', sa.Boolean(), nullable=True),
    sa.Column('banned_at', sa.DateTime(), nullable=True),
    sa.Column('ban_reason', sa.String(), nullable=True),
    sa.Column('notification_settings', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('referral_code'),
    sa.UniqueConstraint('username')
    )
    op.create_index('idx_user_email', 'User', ['email'], unique=False)
    op.create_index('idx_user_role', 'User', ['role'], unique=False)
    op.create_index('idx_user_username', 'User', ['username'], unique=False)
    op.create_table('Account',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('provider', sa.String(), nullable=False),
    sa.Column('provider_account_id', sa.String(), nullable=False),
    sa.Column('refresh_token', sa.String(), nullable=True),
    sa.Column('access_token', sa.String(), nullable=True),
    sa.Column('expires_at', sa.Integer(), nullable=True),
    sa.Column('token_type', sa.String(), nullable=True),
    sa.Column('scope', sa.String(), nullable=True),
    sa.Column('id_token', sa.String(), nullable=True),
    sa.Column('session_state', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['User.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider', 'provider_account_id', name='uq_provider_account')
    )
    op.create_index('idx_account_user_id', 'Account', ['user_id'], unique=False)
    op.create_table('Verification',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('identity_verified', sa.Boolean(), nullable=False),
    sa.Column('license_verified', sa.Boolean(), nullable=False),
    sa.Column('verification_documents', sa.String(), nullable=True),
    sa.Column('identity_name', sa.String(), nullable=True),
    sa.Column('identity_phone', sa.String(), nullable=True),
    sa.Column('identity_birth_date', sa.String(), nullable=True),
    sa.Column('identity_gender', sa.String(), nullable=True),
    sa.Column('identity_verified_at', sa.DateTime(), nullable=True),
    sa.Column('pass_transaction_id', sa.String(), nullable=True),
    sa.Column('license_number', sa.String(), nullable=True),
    sa.Column('license_name', sa.String(), nullable=True),
    sa.Column('license_image_url', sa.String(), nullable=True),
    sa.Column('license_submitted_at', sa.DateTime(), nullable=True),
    sa.Column('license_status', sa.String(), nullable=True),
    sa.Column('license_rejection_reason', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['User.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('pass_transaction_id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index('idx_verification_pass_transaction_id', 'Verification', ['pass_transaction_id'], unique=False)
    op.create_index('idx_verification_user_id', 'Verification', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_verification_user_id', table_name='Verification')
    op.drop_index('idx_verification_pass_transaction_id', table_name='Verification')
    op.drop_table('Verification')
    op.drop_index('idx_account_user_id', table_name='Account')
    op.drop_table('Account')
    op.drop_index('idx_user_username', table_name='User')
    op.drop_index('idx_user_role', table_name='User')
    op.drop_index('idx_user_email', table_name='User')
    op.drop_table('User')
    # ### end Alembic commands ###
